sudo: required
language: c
compiler:
  - gcc

before_script:
  - sudo apt-get update
  - sudo apt-get install kbuild libgc-devel
  - git submodule init
  - git submodule update

script:
  - kmk bootstrap1
  - kmk bootstrap2
  - kmk bootstrap3
