SUB_DEPTH = .
BUILD_TYPE ?= debug
include $(KBUILD_PATH)/subheader.kmk
include $(PATH_CURRENT)/Kmk/OBJC.kmk

include $(PATH_CURRENT)/objcrt/Makefile.kmk
include $(PATH_CURRENT)/objpak/Makefile.kmk

include $(PATH_CURRENT)/objc/Makefile.kmk

PKGNAME = JXObjC-$(KBUILD_TARGET)_$(KBUILD_TARGET_ARCH).tar.gz
PKGDIRS = lib bin include

package:
	tar -C $(PATH_INS) -cvzf $(PKGNAME) $(PKGDIRS)

cleandoc:
	rm -rf doc/masterTOC.html doc/Runtime

include $(FILE_KBUILD_SUB_FOOTER)
