SUB_DEPTH = ..
include $(KBUILD_PATH)/subheader.kmk

LIBRARIES += objcrt objcrtr

objcrt_TEMPLATE = OBJC
objcrt_SOURCES = Block.m Exceptn.m Message.m Object.m OutOfMem.m crt.m

objcrtr_EXTENDS = objcrt
objcrtr_EXTENDS_BY = appending
objcrtr_OBJCFLAGS = -refcnt
objcrtr_DEFS = OBJC_REFCNT
objcrtr_DEPS = $(objcrt_1_TARGET)

include $(FILE_KBUILD_SUB_FOOTER)