SUB_DEPTH = ..
include $(KBUILD_PATH)/subheader.kmk

LIBRARIES += objcrt objcrt_s

objcrt_TEMPLATE = OBJC
objcrt_SOURCES = Block.m Exceptn.m Message.m Object.m OutOfMem.m crt.m

objcrt_s_EXTENDS = objcrt
objcrt_s_EXTENDS_BY = appending
objcrt_s_OBJCFLAGS = -dl -pic
objcrt_s_DEPS = $(objcrt_1_TARGET)

include $(FILE_KBUILD_SUB_FOOTER)