/* Copyright (c) 2016 D. Mackay. All rights reserved. */

#ifndef CONSTSTR_H__
#define CONSTSTR_H__

#include "OCString.h"

/*!
 * @abstract Constant text string
 * @discussion A string literal generated by the compiler. Strictly not to be
 * used outwith that context. Do not make any constant strings yourself, as they
 * receive special-case memory management.
 * @indexgroup Collection
 */
@interface ConstantString : String
@end

#endif
